[package]
name = "thehehfocus/replicador"
description = "Simple library for replication structure."

authors = ["thehehfocus"]

license = "MIT"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"

realm = "shared"
exclude = ["rokit.toml", ".vscode"]

[dependencies]